// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yq0IqgZ6jckWHUlooHrnpHz6dawZjrU',
    appId: '1:371939747884:web:1fffbcda63a7b1c9be4989',
    messagingSenderId: '371939747884',
    projectId: 'tp3flutter-6b791',
    authDomain: 'tp3flutter-6b791.firebaseapp.com',
    storageBucket: 'tp3flutter-6b791.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbFMel7xq2q6h9b5wOt0MCxUEJ6prxPeI',
    appId: '1:371939747884:android:b926ac4beda727ddbe4989',
    messagingSenderId: '371939747884',
    projectId: 'tp3flutter-6b791',
    storageBucket: 'tp3flutter-6b791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRqCgqDjL0VLSVLjyRc-u8Lx9g-cPW37o',
    appId: '1:371939747884:ios:e904643112973b01be4989',
    messagingSenderId: '371939747884',
    projectId: 'tp3flutter-6b791',
    storageBucket: 'tp3flutter-6b791.firebasestorage.app',
    iosBundleId: 'com.example.tp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRqCgqDjL0VLSVLjyRc-u8Lx9g-cPW37o',
    appId: '1:371939747884:ios:e904643112973b01be4989',
    messagingSenderId: '371939747884',
    projectId: 'tp3flutter-6b791',
    storageBucket: 'tp3flutter-6b791.firebasestorage.app',
    iosBundleId: 'com.example.tp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5yq0IqgZ6jckWHUlooHrnpHz6dawZjrU',
    appId: '1:371939747884:web:cad909841fc01b76be4989',
    messagingSenderId: '371939747884',
    projectId: 'tp3flutter-6b791',
    authDomain: 'tp3flutter-6b791.firebaseapp.com',
    storageBucket: 'tp3flutter-6b791.firebasestorage.app',
  );

}